### ISSUE TITLE
Error compling under Arduino IDE for Due with Ethernet shield

### ISSUE THREAD

**Issue by terryzar** [khoih-prog/EthernetWebServer_SSL#15]
### Describe the bug

Arduino IDE compile error for both the MQTTClient_SSL.ino and MQTTClient_SSL_Complex.ino examples:
Here is output from the Arduino IDE:

libraries\EthernetWebServer_SSL-main\SSLClient\SSLClientParameters.cpp.o: In function `std::vector<char, std::allocator<char> >::_M_check_len(unsigned int, char const*) const':

c:\users\tzarnowski\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1\arm-none-eabi\include\c++\4.8.3\bits/stl_vector.h:1339: undefined reference to `std::__throw_length_error(char const*)'

collect2.exe: error: ld returned 1 exit status

### Steps to Reproduce

Open either of the examples in the Arduino IDE and compile for Arduino Due

### Expected behavior

No compiler errors

### Actual behavior

Compile error as described above

### Debug and AT-command log (if applicable)

NA

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.12) 
* `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0) - Not used, is and ESP device required??  I have Arduino Due with W5100 Ethernet shield

  * Operating system Windows 7

  
### Example

```
Arduino IDE version: 1.8.13
ESP32 Core Version 1.0.5
OS: Ubuntu 20.04 LTS
Linux xy-Inspiron-3593 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:
1. ...
2. ...
3. ...
4. ...
```

**Comment by khoih-prog** [comment]
I can compile without any error. Check your installation and read and follow the [**Prerequisites**](https://github.com/khoih-prog/EthernetWebServer_SSL#prerequisites).

![Selection_112](https://user-images.githubusercontent.com/57012152/155760598-379251de-21a0-4412-bc0c-e77e111b67b9.png)
