### ISSUE TITLE
Licensing of SSLClient

### ISSUE THREAD

**Issue by celeron55** [khoih-prog/EthernetWebServer_SSL#16]
It appears this project is using OPEnSLab-OSU/SSLClient, which is a GPL 3.0 licensed library.

However, in this project's code base the library has been marked as if it was MIT licensed.

What happened? Is there permission to do this?

**Comment by khoih-prog** [comment]
Thanks for the info, which I wasn't aware of.

Will modify the licence ASAP to `GPLv3.0`

**Comment by khoih-prog** [comment]
Done with [**EthernetWebServer_SSL** releases v1.7.7](https://github.com/khoih-prog/EthernetWebServer_SSL/releases/tag/v1.7.7). Thanks.

---

### Releases v1.7.7

1. Change license from `MIT` to `GPLv3`. Check [**Licensing of SSLClient** #16](https://github.com/khoih-prog/EthernetWebServer_SSL/issues/16)
