### ISSUE TITLE
Pull in OPEnSLab-OSU's SSLClient v1.6.11

### ISSUE THREAD

**Issue by marcelstoer** [khoih-prog/EthernetWebServer_SSL#17]
Apparently your code uses/is based on OPEnSLab-OSU's SSLClient v1.6.9. That version has issues like the one commented on here https://github.com/khoih-prog/EthernetWebServer_SSL/blob/main/examples/MQTTClient_SSL_Auth/MQTTClient_SSL_Auth.ino#L72 (OPEnSLab-OSU/SSLClient#9).

Pulling in the changes for 1.6.11 would allow you to remove the work-arounds: [v1.6.9...v1.6.11](https://github.com/OPEnSLab-OSU/SSLClient/compare/v1.6.9...v1.6.11)

**Comment by khoih-prog** [comment]
Hi @marcelstoer 

The new [**EthernetWebServer_SSL releases v1.7.8**](https://github.com/khoih-prog/EthernetWebServer_SSL/releases/tag/v1.7.8) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/EthernetWebServer_SSL#contributions-and-thanks)

Best Regards,

---

### Releases v1.7.8

1. Sync with [**SSLClient v1.6.11**](https://github.com/OPEnSLab-OSU/SSLClient/releases/tag/v1.6.11). Check [**Pull in OPEnSLab-OSU's SSLClient v1.6.11** #17](https://github.com/khoih-prog/EthernetWebServer_SSL/issues/17)
2. Add example [**AWS_IoT**](examples/AWS_IoT)
3. Change default SS pin for RP2040 using [**ArduinoCore-mbed** core](https://github.com/arduino/ArduinoCore-mbed) to 17 from 5 to be the same as [**arduino-pico** core](https://github.com/earlephilhower/arduino-pico)
4. Update `Packages' Patches`

**Comment by marcelstoer** [comment]
Thank you
