### ISSUE TITLE
fatal error: vector

### ISSUE THREAD

**Issue by ggerminiani** [khoih-prog/EthernetWebServer_SSL#30]
I'm trying to run the example WeClient_SSL, but I get this error:

```

In file included from C:\Users\gustavo\Documents\Arduino\libraries\EthernetWebServer_SSL\src/SSLClient/SSLClient.h:28:0,
                 from C:\Users\gustavo\Documents\Arduino\libraries\EthernetWebServer_SSL\src/EthernetWebServer_SSL.hpp:152,
                 from C:\Users\gustavo\Documents\Arduino\libraries\EthernetWebServer_SSL\src/EthernetWebServer_SSL.h:78,
                 from C:\Users\gustavo\AppData\Local\Temp\.arduinoIDE-unsaved20221112-19088-rop1ck.rak6\WebClient_SSL\defines.h:530,
                 from C:\Users\gustavo\AppData\Local\Temp\.arduinoIDE-unsaved20221112-19088-rop1ck.rak6\WebClient_SSL\WebClient_SSL.ino:14:
C:\Users\gustavo\Documents\Arduino\libraries\EthernetWebServer_SSL\src/SSLClient/SSLClientParameters.h:33:10: fatal error: vector: No such file or directory
 #include <vector>
          ^~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
```

- Arduino Mega
- Shiled ethernet (w5100)
- Arduino IDE 2.0.3
- AVR Boards 1.8.2
- EthernetWebServer_SSL 1.9.3

Could someone help me?

**Comment by khoih-prog** [comment]
Hi @ggerminiani 

Check item 6 of [**Currently supported Boards**](https://github.com/khoih-prog/EthernetWebServer_SSL#currently-supported-boards)

> AVR Mega1280, 2560, ADK.. SSL WebClient not supported yet. Check https://github.com/mike-matera/ArduinoSTL/issues/56

Some people could make it working somehow by using `Arduino AVR board to 1.8.2`. Try using Arduino IDE v1.8.19, not v2.0.0+ and see.

This is not the issue of this library and I'm closing it now. Ask on [**ArduinoSTL** library](https://github.com/mike-matera/ArduinoSTL) or **Arduino Forum** if you need help.

Good Luck,
