### ISSUE TITLE
webserver SSL

### ISSUE THREAD

**Issue by gitTinker** [khoih-prog/EthernetWebServer_SSL#5]
This is either a documentation request, or an example request.

The section "[WebServer and non TLS/SSL WebClient Usage](https://github.com/khoih-prog/EthernetWebServer_SSL#webserver-and-non-tlsssl-webclient-usage)" implies that WebServer does not run as https.
Also the server examples use port 80 (not 443) confirming non-SSL.

Please **provide an example of a HTTPS (**port 443**) webserver**.

or, if HTTPS is _not_ possible, please update the [readme ](https://github.com/khoih-prog/EthernetWebServer_SSL/blob/main/README.md)to specifically state this functionality is not available.
(I've spent most of my last 2 evenings looking through this project for an HTTPS server solution. eg: applying the client SSL to the webserver example)

**Comment by khoih-prog** [comment]
Read carefully the [Features](https://github.com/khoih-prog/EthernetWebServer_SSL#features)

#### Features

This [EthernetWebServer_SSL library](https://github.com/khoih-prog/EthernetWebServer_SSL) is a simple yet complete **TLS/SSL WebClient** and **non-TLS/SSL WebServer** library for **Teensy, SAM DUE, Arduino SAMD21, Adafruit SAMD21/SAMD51, Adafruit nRF52, ESP32/ESP8266, STM32, etc.** boards using Ethernet shields. The functions are similar and compatible to those of [`ESP32 WebServer`](https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer) and [`ESP8266WebServer`](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer) libraries to make life much easier to port sketches from ESP8266/ESP32.
